#!/usr/bin/env bash
# A Bash script that creates a /var/run/holbertonscript.pid file,
# displays a text indefinitely,
# displays a text when receiving a SIGTERM signal,
# displays a text when receiving a SIGINT signal,
# deletes the file and terminates itself when receiving a SIGQUIT or SIGTERM signal

file='/var/run/holbertonscript.pid'
echo $$ > $file 

trap "echo 'I hate the kill command'; rm $file; exit 1" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm $file; exit 1" SIGQUIT

while :
do
    echo "To infinity and beyond"
    sleep 2
done
