#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes.

minute=1
hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $minute -le 59 ]
    do
	echo "$minute"
	(( minute++ ))
    done
    minute=1
    (( hour++ ))
done
