#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes.

minutes=1
hours=0

while [ $hours -le 12 ]
do
    echo "Hours: $hours"
    hours=$(( hours+1 ))
    while [ $minutes -le 59 ]
    do
	echo "$minutes"
	minutes=$(( minutes+1 ))
    done
    minutes=1
done
