#!/usr/bin/env bash
# Change localhost and facebook.com ip address
cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
sed -i '1 i\8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
